### ISSUE TITLE
Suport Non Ed25519 Keys in responses

### ISSUE THREAD

**Issue by elucidsoft** [elucidsoft/dotnet-stellar-sdk#100]
See the Java PR: https://github.com/stellar/java-stellar-sdk/pull/126

**Comment by Kirbyrawr** [comment]
Hi, i can do it i think, tomorrow i will have it probably

**Comment by robertDurst** [comment]
If you are curious, ref: https://github.com/stellar/go/issues/536

**Comment by Kirbyrawr** [comment]
Closing as this was merge
