### ISSUE TITLE
Remove KeyPair dependency from requests and responses

### ISSUE THREAD

**Issue by Kirbyrawr** [elucidsoft/dotnet-stellar-sdk#105]
Since we are trying to follow the Java implementation would be cool to start removing the KeyPair parameter from the requests and responses and make it a string.

https://github.com/stellar/java-stellar-sdk/pull/139

**Comment by Kirbyrawr** [comment]
What do you think @elucidsoft

**Comment by Kirbyrawr** [comment]
Hi @elucidsoft i finished this task, however one test is failing.
The problem is that is trying to Assert.AreEqual two keypairs but one have secret seed and the other throw an exception, this return not equal failing the test, what can i do here?

My branch: https://github.com/Kirbyrawr/dotnet-stellar-sdk/tree/remove-keypair-dependency
Test error line: https://github.com/Kirbyrawr/dotnet-stellar-sdk/blob/f4b66e975fff9389f79d2215d12c7bfb47d63e3f/stellar-dotnet-sdk-test/TransactionTest.cs#L48

Thanks in advance.

**Comment by elucidsoft** [comment]
I'll look into this as soon as I get a chance.

**Comment by michaeljmonte** [comment]
@Kirbyrawr I am unable to replicate the issue in your branch. All tests run and pass.

**Comment by Kirbyrawr** [comment]
@michaeljmonte Hmm, how weird, well if all is ok should i do the pull request?

**Comment by michaeljmonte** [comment]
@Kirbyrawr I would check it on your side again, just to be sure.

**Comment by Kirbyrawr** [comment]
Sure, i will!

**Comment by Kirbyrawr** [comment]
Here is the pull request, with branch master merged and all tests passing.
https://github.com/elucidsoft/dotnet-stellar-sdk/pull/143
