### ISSUE TITLE
Existing Chaos.NaCl.Ed25519 conflict with dotnet-stellar-sdk

### ISSUE THREAD

**Issue by bazooka70** [elucidsoft/dotnet-stellar-sdk#107]
On an existing .NET 4.6.2 console application, I have `dlech.Chaos.NaCl` package installed (version 0.1.0).
In my existing code there is a line:

```csharp
var buf = new byte[32];
Chaos.NaCl.Ed25519.KeyPairFromSeed(out byte[] publicKey, out byte[] expandedPrivateKey, buf);
```

After installing the `dotnet-stellar-sdk`, and trying to compile I get an error (on the reference to `Chaos.NaCl.Ed25519`):

`Error	CS0433	The type 'Ed25519' exists in both 'Chaos.NaCl, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' and 'stellar-dotnetstandard-sdk, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'	Stellar	D:\Projects\Stellar\Encryption.cs`

What can I do to resolve this issue?
P.S: This might not be a `stellar-dotnetstandard-sdk` *bug*, but I'm not a .NET expert and the face the both packages use a different namespace makes me wonder what could cause this.

Please advice.

**Comment by bazooka70** [comment]
Hi @Kirbyrawr , I don't use `stellar_dotnet_sdk.chaos.nacl` (this namespace does not exists).
My project already uses `Chaos.NaCl`. As you can see, I specify the the full namespace of `Chaos.NaCl`.
I this that stellar_dotnet_sdk somehow overloads this namespace.

https://github.com/elucidsoft/dotnet-stellar-sdk/blob/master/stellar-dotnet-sdk/chaos.nacl/Ed25519.cs

But I'm not sure how to resolve this :/

**Comment by Kirbyrawr** [comment]
Hi, can i get a screenshot of your solution (Collapsed) i want to see if you have any duplicates there.

**Comment by Kirbyrawr** [comment]
Hm, what's in your encryption class? Maybe there you have something.

**Comment by bazooka70** [comment]
@Kirbyrawr "what's in your encryption class?" Nothing at the moment. I only have a `Test` method:

        ```
internal static void Test()
        {            
            var buf = new byte[32];
            Chaos.NaCl.Ed25519.KeyPairFromSeed(out byte[] publicKey, out byte[] expandedPrivateKey, buf);
        }
```

I will create a new fresh project with `Chaos.NaCl` and `stellar_dotnet_sdk` packages and see if this consists...

**Comment by Kirbyrawr** [comment]
Let us know! Thanks.

**Comment by bazooka70** [comment]
![project](https://user-images.githubusercontent.com/36622310/45801201-6f766c80-bcb3-11e8-83fb-cf143df2b16c.png)

**Comment by bazooka70** [comment]
@Kirbyrawr , I uploaded a screenshot of a brand new project with only the dlech.Chaos.NaCl and stellar_dotnet_sdk packages installed. 

p.s: sorry for closing the issue. it was a mistake.

**Comment by Kirbyrawr** [comment]
Can you try to compile the DLL from this code and use that instead of the Nuget, i believe the Nuget have an old version with the old names.

**Comment by bazooka70** [comment]
I will give it a try and let you know...
p.s: maybe it will be a good idea to bump the newer version to NuGet?

**Comment by bazooka70** [comment]
@Kirbyrawr , Yes compiling the DLL from this code  makes the CS0433 error is gone! 
Thanks a million!
Is it possible to upload the latest version to NuGet please?

**Comment by Kirbyrawr** [comment]
Sure we will work on it, i'm glad you got it working, thank you and
apologies for the late time response since i'm working ^^"

**Comment by bazooka70** [comment]
@Kirbyrawr, You are VERY helpful and kind! thank you for your time and effort :)
Now I need to figure out how to share this DLL via TFS. never done this before.
