### ISSUE TITLE
Redo Network usage

### ISSUE THREAD

**Issue by elucidsoft** [elucidsoft/dotnet-stellar-sdk#109]
To remove the issues around thread safety and dependency on a static variable the Network usage should be refactored.  

Should use the builder pattern that's already used through the sdk to create a Server object instanced based on a specific Network.

Example:
`using(var server = Server.Use(Network.Public).Create())`

**Comment by mrtpain** [comment]
Please also make 
`private static readonly string PUBLIC` and
`private static readonly string TESTNET` publicly available similar to the JS SDK [here](https://github.com/stellar/js-stellar-base/blob/master/src/network.js) or I can open a pull request.

**Comment by Khay-EMMA** [comment]
Please consider the issues with setting up a Network.

 Transactions always returns tx_bad_auth. I have read in various docs that this is a result of an unset Network.

PS: I have used Network.UseTestNetwork() but it still has the same issues.

**Comment by elucidsoft** [comment]
@Khay-EMMA Can you post a Gist of your code so I can take a look at your specific scenario?  Also I will make resolving this a higher priority for me.

**Comment by Kirbyrawr** [comment]
Hi, i think the problem of @Khay-EMMA is fixed already, @Khay-EMMA can you confirm it?

Kind regards

**Comment by elucidsoft** [comment]
Just to update, @Khay-EMMA issue is not related to this issue.  It was something else, but we do still need to redo the Network usage so its thread safe.  The issue with the Network is you could potentially fall into a race condition if using it in a multi-threaded scenario.

**Comment by Khay-EMMA** [comment]
Okay... Thanks a lot for the information. My issue has already been fixed by a member of your team on Keybase and it had nothing to do with the Network Usage. Sorry for the Inappropriate post and thanks for the assistance.
