### ISSUE TITLE
Server.SubmitTransaction for an unfunded new account fails

### ISSUE THREAD

**Issue by bazooka70** [elucidsoft/dotnet-stellar-sdk#111]
I am using the example [Send Native Assets](https://github.com/elucidsoft/dotnet-stellar-sdk/blob/master/docfx/examples/send_native_assets.md)

My source account has 10,000  lumen (got that via the `TestNetFriendBot`). 
If I send 1000 xlm to an existing destination account all is fine.

However, if I send  funds to a fresh unfunded  account (created via `KeyPair.Random()`)  the `Server.SubmitTransaction` response  with no `Hash` in the result and `response.SubmitTransactionResponseExtras.ExtrasResultCodes.TransactionResultCode` is set to `tx_failed` with `op_no_destination`.

I confused since the [FAQ](https://www.stellar.org/faq/) says:

> You can fund an account by sending 1 lumen to it...

So I realize that there should be a minimum reserve of 2.5 lumens for destination. but I'm sending 1000 to it. 

Did I misunderstand the consensus? What Im I doing wrong?
Please advice.

**Comment by Kirbyrawr** [comment]
Hi there just woke up, you need to do a CreateAccount Operation not a
Payment Operation if it's not created.

**Comment by bazooka70** [comment]
Hi @Kirbyrawr  and good morning :)
Thanks for you reply.
Do I need to send funds in order to `CreateAccount ` (and Sign?)? is it the same as `SubmitTransaction`?

**Comment by Kirbyrawr** [comment]
Hi there good morning, you can specify how much do you want to have as
starting balance, i'm not sure if the create account operation have in mind
the base fee and do this automatically, i think yes, just try in testnet i
would say.

It's more or less like another operation, you create it, sign it and send
it.

**Comment by elucidsoft** [comment]
Hello,

If you could please direct general help questions to the [Stellar Stack Exchange](https://stellar.stackexchange.com/) that would be better. Since this is not an actual issue with the SDK I will be closing this issue.  

As @Kirbyrawr stated, you need to Create an account, KeyPair only generates the Keys but does not create the account on the network.  You will then need to fund the account with minimum balance before you can use it.  Thanks!

**Comment by bazooka70** [comment]
@elucidsoft , Thanks for the comment. I never thought  `CreateAccount` was the answer. sorry.
It works fine now :+1:
