### ISSUE TITLE
DataContractAttribute missing for lot of classes, for example, Balance

### ISSUE THREAD

**Issue by henryhwang** [elucidsoft/dotnet-stellar-sdk#120]
It seems that the DataContractAttribute missed for all classes which has JsonPropertyAttribute for thier peoperties. This makes the Json serialization of those classes failed. Right now, to do the Json serialization for example for AccountResponse object, you need to create your own ContractResolver with MemberSerialization set to OptIn for its CreateProperties method, such as following,

        public class ForceOptInContractResolver : DefaultContractResolver
        {
            protected override IList<JsonProperty> CreateProperties(Type type, MemberSerialization memberSerialization)
            {
                return base.CreateProperties(type, MemberSerialization.OptIn);
            }
        } 

and use it like this,

        var accountResponseString = JsonConvert.SerializeObject(accountResponse,
                                                              Newtonsoft.Json.Formatting.Indented,
                                                              new ForceOptInContractResolver());

**Comment by elucidsoft** [comment]
Can you provide me with an example that's failing?

**Comment by henryhwang** [comment]
Sure.
 For example,

            AccountResponse accountDetail = ...;
            string accountDetailString = JsonConvert.SerializeObject(accountDetail, Formatting.Indented);
            Console.WriteLine(accountDetailString);

This will give you error. Instead you could do that as following

            AccountResponse accountDetail = ...;
            var settings = new JsonSerializerSettings();
            settings.ContractResolver = new ForceOptInContractResolver();
            var accountDetailString = JsonConvert.SerializeObject(accountDetail,
                            Formatting.Indented,
                            settings);
            Console.WriteLine(accountDetailString);        

        private class ForceOptInContractResolver : DefaultContractResolver
        {
            protected override IList<JsonProperty> CreateProperties(Type type, MemberSerialization memberSerialization)
            {
                return base.CreateProperties(type, MemberSerialization.OptIn);
            }
        }

**Comment by elucidsoft** [comment]
You can't use JsonSingelton to do this?

**Comment by henryhwang** [comment]
JsonSingelton is for Deserialize from json string to response object, right? I was talking about SErialize from resonse object to json string.

**Comment by elucidsoft** [comment]
Oh I see, yes the SDK doesn't really support that atm. We can add it as a
feature request.

**Comment by fracek** [comment]
I will have a shot at this since I had the same problem. I will make sure all request/response can be deserialized as well as serialized.

**Comment by elucidsoft** [comment]
I have an idea on how to do this, I think what needs to be done is to get
JsonSingelton to Serialize. I think this would involve updating each
converter as well to implement their WriteJson implementations? I'm not
100% sure...

**Comment by fracek** [comment]
In most cases the serialization is working out of the box after adding `[JsonObject(MemberSerialization.OptIn)]` to `Response`. Classes like `EffectResponse` and `OperationResponse` need some extra work to serialize the correct `type_i` but it's not bad.

**Comment by elucidsoft** [comment]
Awesome, thanks!
