### ISSUE TITLE
Update version on nuget

### ISSUE THREAD

**Issue by fracek** [elucidsoft/dotnet-stellar-sdk#121]
Hi, would it be possible to update the version on nuget to a more recent one?

**Comment by elucidsoft** [comment]
Yes.  I will do that.

**Comment by fracek** [comment]
Thank you. I really appreciate your work on this project.

**Comment by elucidsoft** [comment]
I uploaded Beta 2 Nuget Package for 2.1.0, I also added support for Source Link.

https://www.nuget.org/packages/stellar-dotnet-sdk/2.1.0-beta2
