### ISSUE TITLE
Stream keeps loop for just first 10 transactions

### ISSUE THREAD

**Issue by henryhwang** [elucidsoft/dotnet-stellar-sdk#123]
When you try to use stream, for transactions for example, the result just keeps loop for the first 10 records.
            Network.UseTestNetwork();
            var server = new Server("https://horizon-testnet.stellar.org/");
            var r = (EventSource) server.Transactions.ForAccount(KeyPair.FromAccountId("XXX...")).Stream(
                (o, message) => { Console.WriteLine($"{message.Hash}"); }
            );
            Console.WriteLine("Start to connect ...");
            await r.Connect();

What you would get as the result from above code is just first 10 transactions for that account looping.

**Comment by elucidsoft** [comment]
I dont seem to have this issue. I was able to keep it open for over 24
hours with no issue.

**Comment by elucidsoft** [comment]
The console has example code

**Comment by elucidsoft** [comment]
Does it do the same thing in the js library? I'll take a look.

**Comment by elucidsoft** [comment]
Ok, I'll elevate this...

**Comment by elucidsoft** [comment]
I sent you an invite on Hangouts if you could accept I would like to screen share because this works for me...

**Comment by elucidsoft** [comment]
Nevermind I see what's happening now...

**Comment by elucidsoft** [comment]
Ok, I think I fixed this can you verify?

**Comment by henryhwang** [comment]
Hi @elucidsoft,
After some checks, I think the real problem is from EventSource. There are 2 places in EventSource to reset LastEventId to null, which should not and make EventSource starts from beginning everytime it tries to reconnect. The better fix should be to comment out those reset for LastEventId, I think, which not only fix the problem from .stream perspective but also makes EventSource works more like js version.

**Comment by elucidsoft** [comment]
I tried that, it didnt seem to work. So my update will update the cursor in url so st least on reconnect it resumes where it left off...

It's not the best solution but it will work for now. Ideally EventSource should be redone completely.

**Comment by aph5nt** [comment]
On 2.1 beta, after receiving the first transaction, the stream falls in a loop, but not for 10 iterations but forever.
