### ISSUE TITLE
Fix nuget package to not include stellar-dotnet-sdk and stellar-dotnetstandard-sdk at the same time

### ISSUE THREAD

**Issue by ORuban** [elucidsoft/dotnet-stellar-sdk#129]
**Problem**
 Nuget package for .NETStandard contains both stellar-dotnet-sdk and  stellar-dotnetstandard-sdk assemblies and so compiler doesn't know what to use.

**To Reproduce**
- Create a netstandard2.0 project
- Add nuget package stellar-dotnet-sdk 2.1.0-beta2
- Try to use any type from stellar_dotnet_sdk namespace

After that, build fails with the following error: 
`The type '<TypeName>' exists in both 'stellar-dotnet-sdk, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' and 'stellar-dotnetstandard-sdk, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'	`

**Comment by elucidsoft** [comment]
A new nuget package has been release 2.1-beta3 that resolves this...
