### ISSUE TITLE
Unable to process byebye message

### ISSUE THREAD

**Issue by aph5nt** [elucidsoft/dotnet-stellar-sdk#130]
**Describe the bug**
Stream throws on "byebye" message

**To Reproduce**
1. Download Beta2 source code
2. Reference net standard version into your project
3. Start stream in your console app
4. Send a stellar transaction to the listened address
5. Process hello message, process operation message
6. Process byebye message

**Expected behavior**
Should not throw, pagination token should be updated

**Screenshots**
https://imgur.com/FIG5N95

**Desktop (please complete the following information):**
 - OS: win10

**Comment by aph5nt** [comment]
Also, the stream is processing the same transaction n times!

**Comment by elucidsoft** [comment]
I really need to rewrite the EventSource code, I may take a stab at this
tonight.

**Comment by aph5nt** [comment]
ok keep me posted, for now, I will stick to long polling mechanism,

**Comment by elucidsoft** [comment]
Did you try the latest code or just the release?

**Comment by aph5nt** [comment]
the release version

**Comment by elucidsoft** [comment]
A new nuget was released that should help alleviate this issue. It's not addressed 100% though.

**Comment by elucidsoft** [comment]
Finally fixed.
