### ISSUE TITLE
HAL and followings Links

### ISSUE THREAD

**Issue by fracek** [elucidsoft/dotnet-stellar-sdk#133]
**Is your feature request related to a problem? Please describe.**

Responses usually contain a collection of `Links` that point to other resources related to it, for example `LedgerResponse` has links to `OperationResponse` etc. It would be very useful to be able to follow these links somehow.

**Describe the solution you'd like**

I have an idea on how to implement this feature:

1. Change the type of `Link` to `Link<TResponse>`
2. Add the method `FollowLink<TResponse>(Link<TResponse> link)` to server
3. Maybe add a method `Follow` to `Link`, similar to what we have in `Page<T>`?

Templated links pose a challenge, but we can use [Tavis.UriTemplates](https://github.com/tavis-software/Tavis.UriTemplates). What do you think about adding this dependency?

I can implement this if you are ok with it, mostly I want your opinion if you are fine adding a new dependency and if you prefer the follow method on the link or server (or both).

**Comment by elucidsoft** [comment]
Can we implement just the very minimal of what we need from that library?
I would be a bit concerned about having this many chained references and
the garbage collector never being able to dispose of anything as well.
Thoughts on that?
