### ISSUE TITLE
Nuget Package for beta3 is empty

### ISSUE THREAD

**Issue by fracek** [elucidsoft/dotnet-stellar-sdk#142]
**Describe the bug**

I tried to update to beta3 but it seems the nuget package is missing the library assembly.

**To Reproduce**
1. Create a new `netcoreapp2.1` projec
2. Add the beta3 package
3. Build
4. See error `Program.cs(2,7): error CS0246: The type or namespace name 'stellar_dotnet_sdk' could not be found (are you missing a using directive or an assembly reference?) [/home/fra/Solution1/ConsoleApp1.csproj]`

**Desktop (please complete the following information):**
 - OS: Linux x64

**Additional context**

I unzipped the `.nupkg` file for beta3 and it seems there is nothing inside:

```
[fra@grigio package]$ unzip -l stellar-dotnet-sdk.2.1.0-beta3.nupkg
Archive:  stellar-dotnet-sdk.2.1.0-beta3.nupkg
  Length      Date    Time    Name
---------  ---------- -----   ----
      512  12-29-2018 23:12   _rels/.rels
     2250  12-29-2018 23:12   stellar-dotnet-sdk.nuspec
    11560  12-30-2018 03:31   LICENSE.txt
      465  12-29-2018 23:12   [Content_Types].xml
     1010  12-29-2018 23:12   package/services/metadata/core-properties/02a3dbe679a344058225304888f5270c.psmdcp
---------                     -------
    15797                     5 files
```

If I try to repackage locally using `dotnet pack dotnetstandard/stellar-dotnetstandard-sdk.csproj` I obtain the following nupkg:

```
[fra@grigio lib]$ unzip -l stellar-dotnetstandard-sdk.2.0.0-standard.nupkg 
Archive:  stellar-dotnetstandard-sdk.2.0.0-standard.nupkg
  Length      Date    Time    Name
---------  ---------- -----   ----
      516  12-31-2018 14:17   _rels/.rels
     1134  12-31-2018 14:17   stellar-dotnetstandard-sdk.nuspec
   453632  12-31-2018 14:17   lib/netstandard2.0/stellar-dotnetstandard-sdk.dll
      459  12-31-2018 14:17   [Content_Types].xml
      887  12-31-2018 14:17   package/services/metadata/core-properties/a1865dce52564996b60ed95fe8528148.psmdcp
---------                     -------
   456628                     5 files
```

**Comment by elucidsoft** [comment]
That's odd, I'll take a look and repackage it.

**Comment by elucidsoft** [comment]
I actually don't like the way I set this up, so I am going to redo how Nuget packages are built.
