### ISSUE TITLE
Friendbot not working when using custom Horizon API

### ISSUE THREAD

**Issue by nikolaimaximilian** [elucidsoft/dotnet-stellar-sdk#160]
We have switched our testing a custom Horizon API. But when initializing **Server** with the custom URL, FriendBot is not working. As Friendbot is a service by Steller, that URL should be independent of what is parsed into **Server** - should be configurable and default to the official Stellar URL.

Many thanks,
Nik

**Comment by fracek** [comment]
Can you provide more information? Is your code throwing an exception or it fails silently? Are you using the test network with your Horizon Server or also using a private network?

**Comment by elucidsoft** [comment]
Correct, friendbot only works with Public Horizon

**Comment by elucidsoft** [comment]
In addition I believe the author of friendbot said its broken right now
after latest upgrade. They aware of this but haven't issued a fix fir it
yet.
