### ISSUE TITLE
LedgerResponse failed_transaction_count doesn't support null values

### ISSUE THREAD

**Issue by coj337** [elucidsoft/dotnet-stellar-sdk#162]
**Describe the bug**
Some early ledgers will return null for failed_transaction_count, causing a nullreferenceexception. e.g. https://horizon.stellar.org/ledgers/500.

**To Reproduce**
1. Call server.Ledgers.Ledger(500)
2. Library throws null reference exception

**Expected behavior**
The ledger should be returned with a null value.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: N/A
 - Version: N/A

**Additional context**
N/A

**Comment by fracek** [comment]
@elucidsoft Should we make this nullable or default to 0?

**Comment by coj337** [comment]
I think nullable is better, there's probably a reason they are null and somebody will have a use case for it.

**Comment by elucidsoft** [comment]
I think we can make it nullable, let's add a unit test for as well to test both conditions for whoever does this...
