### ISSUE TITLE
Protocol 11 Support

### ISSUE THREAD

**Issue by elucidsoft** [elucidsoft/dotnet-stellar-sdk#166]
- Operation type names changes (in the XDR)
    manage_offer -> manage_sell_offer,
    create_passive_offer -> create_passive_sell_offer,
    New manage_buy_offer operation.
- Offer IDs are now of int64 type.

It's of note that the operations in Horizon have not changed (manage_offer and manage_passive_offer to manage_sell_offer) and won't change until v0.18.0, but keep it in mind.

**Comment by theaeolianmachine** [comment]
Some useful links:

* https://github.com/stellar/go/pull/1164
* https://github.com/stellar/stellar-protocol/blob/master/core/cap-0006.md
* [XDR files diff](https://github.com/stellar/stellar-core/compare/v10.3.0...v11.0.0#diff-01cb6b2520b4d5097b53837c1c18c5a3) - this shows all changes between v10.3.0 and v11.0.0 in Stellar Core — you'll need to just look at the changes in `src/xdr` (realistically any file that ends with a `.x` extension).

Let me know if you have any questions!

**Comment by elucidsoft** [comment]
This should be done, the commit has been merged and everything looked ok. All 399 unit tests are passing.

**Comment by theaeolianmachine** [comment]
Saw the new release got cut — feel free to close out when you're good! (We're tracking this internally for the migration of the network to protocol 11).
