### ISSUE TITLE
Horizon v.0.18.0 Compatibility

### ISSUE THREAD

**Issue by theaeolianmachine** [elucidsoft/dotnet-stellar-sdk#168]
With Horizon v0.18.0, the following breaking changes will occur:

- The `manage_offer` endpoint will be renamed to `manage_sell_offer`
- The `create_passive_offer` endpoint will be renamed to `create_passive_sell_offer`.

We suggest for all Stellar SDK maintainers to offer compatibility between `v.0.17.X` type names as well as the new names in `v.0.18.0` in order to make the transition process from `v0.17.X` to `v0.18.0` to go smoother.

Let me know if you have any questions!

**Comment by fracek** [comment]
What changes is the value of the `type` field of operation and effects responses, correct? In that case I believe it doesn't require any change on our part since we use `type_i`.

**Comment by elucidsoft** [comment]
I believe this is resolved, can you concur?

**Comment by fracek** [comment]
I don't think we ever use that value directly. I think we don't need any change to be compatible with v0.18

**Comment by theaeolianmachine** [comment]
Yeah, you guys should be good to go! the `type_i` shouldn't be changing.
