### ISSUE TITLE
12 manage buy offer operation not supported

### ISSUE THREAD

**Issue by mvaneijk** [elucidsoft/dotnet-stellar-sdk#177]
**Describe the bug**
Protocol 11 not fully supported

**To Reproduce**
Get operations for ledger 24451929, this contains the not supported 
type: 12 manage buy offer operation

see laboratory: https://tinyurl.com/yxjp6kob

**Expected behavior**
No error

**Additional context**
It is missing in this file: 
dotnet-stellar-sdk/stellar-dotnet-sdk/responses/OperationDeserializer.cs

**Comment by elucidsoft** [comment]
We're on it.

**Comment by elucidsoft** [comment]
Confirmed this is an issue that needs addressing.

**Comment by elucidsoft** [comment]
This has been resolved, please update to the latest NuGet package 2.2.28 or source.
