### ISSUE TITLE
Create Account in private network

### ISSUE THREAD

**Issue by moryekram** [elucidsoft/dotnet-stellar-sdk#179]
Hi, I am creating a private custom stellar network.
How can i create new account?
```Network network = new Network("My Standalone Network ; July 2019");```
```Server server = new Server("http://192.168.122.114:8000");```
`Network.Use(network);`
`var sourceKeyPair = KeyPair.FromSecretSeed("root secret key");`

and what should I do after that?

**Comment by fracek** [comment]
You need to create a transaction with a `CreateAccountOperation` in it. You want to do something like (haven't compiled this code, so it may need fixing)

``` csharp
Network.Use(network);
using (var server = new Server("...."))
{
    var account = await server.Accounts.Account(sourceKeyPair.AccountId);
    var dest = KeyPair.Random();
    var balance = "123.45"; // starting balance, in XML
    var op = new CreateAccountOperation.Builder(dest, balance).Build();
    var tx = new Transaction.Builder(account).AddOperation(op).Build();
     // sign transaction
    tx.Sign(sourceKeyPair);
    var response = await server.SubmitTransaction(tx);
    if (response.IsSuccess())
    { 
        // Success
    } else {
        // Something went wrong
    } 
}
```

**Comment by moryekram** [comment]
Thanks and excuse me for delay, because my server has been down.
Your answer helped me.
