### ISSUE TITLE
 Support for SEP 10 challenge transaction

### ISSUE THREAD

**Issue by ire-and-curses** [elucidsoft/dotnet-stellar-sdk#182]
SEP 10 describes a [specific form](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0010.md#response) for the "challenge" transaction used for authentication. Providing a helper at the SDK level makes sense to save users from reimplementing the spec.

Here are example implementations in [Go](https://github.com/stellar/go/pull/1468) and [JS](https://github.com/stellar/js-stellar-sdk/pull/375).

**Comment by elucidsoft** [comment]
I am waiting for SEP-0010 v2.0 spec since there seem to be some disagreements on v1.0 implementation details.

**Comment by ire-and-curses** [comment]
Not sure what you mean by "v2 spec"? Wording has been clarified with respect to the base64 cryptographic random string in [stellar-protocol:#366](https://github.com/stellar/stellar-protocol/pull/366).

JS and Go implementations have been updated to reflect the intended behaviour:
JS: https://github.com/stellar/js-stellar-sdk/pull/396
Go: https://github.com/stellar/go/pull/1569

Go fix expected to merge to master for release by end of the week (Aug 10).

So you should be good to go unless there are other concerns?

**Comment by elucidsoft** [comment]
In the issues under the spec it was labeled as such...

https://github.com/stellar/stellar-protocol/issues/331

**Comment by ire-and-curses** [comment]
Thanks for the link, that makes sense now. I asked for clarification internally at SDF. I'm told that these are future improvement ideas being recorded for reference. As far as I know there is no active drive to imminently replace the v1 spec. SEP 10 as it stands is being built out by a number of groups. I defer to you here: whether to implement sooner or wait for a while is of course your call.

**Comment by elucidsoft** [comment]
I gave the team the all is clear to implement this, but I did want to clarify. Thanks!
