### ISSUE TITLE
Deprecate/Remove Network singleton

### ISSUE THREAD

**Issue by fracek** [elucidsoft/dotnet-stellar-sdk#197]
This is probably related to #109 and #104.

I noticed the [java sdk](https://github.com/stellar/java-stellar-sdk/pull/224) and [js sdk](https://github.com/stellar/js-stellar-base/pull/207) removed the Network singleton that we also have.

AFAIK we only need to mark things obsolete, no new feature is required since everything was implemented in #104.

**Comment by elucidsoft** [comment]
I guess since we have released a major since this was implemented we can go ahead and close?
