### ISSUE TITLE
Add support for retrieve Account Data

### ISSUE THREAD

**Issue by Kirbyrawr** [elucidsoft/dotnet-stellar-sdk#20]
Hi there, correct me if i'm wrong but i think that we don't have any way for retrieve the data that has been set in a account.

I have some code done (Mostly a DataSerializer) but i still need to polish it and test it, however i will just open this issue just in case it's already done.

Thanks!
![image](https://user-images.githubusercontent.com/3259762/40207061-e304d6de-5a32-11e8-91af-87c02cd2aebc.png)

**Comment by Kirbyrawr** [comment]
So the questions are:
-Do the SDK have anything for retrieve data? 
-If not, is this the correct way to do it? I just took a look to AssetDeserializer and did it almost the same. 
-With this you would be able to do something like:
accountResponse.Data where you would have a dictionary of <string, string>

**Comment by elucidsoft** [comment]
Can you post a Gist of the code you used?

**Comment by elucidsoft** [comment]
I think it should be done the same way it was done for the Java SDK here: https://github.com/stellar/java-stellar-sdk/pull/85

**Comment by Kirbyrawr** [comment]
Created pull request https://github.com/elucidsoft/dotnet-stellar-sdk/pull/23

**Comment by Kirbyrawr** [comment]
It should work :)

**Comment by Kirbyrawr** [comment]
Closing as this is now completed
