### ISSUE TITLE
'Public member 'sign' on type 'Builder' not found.' when I try to sign a transaction

### ISSUE THREAD

**Issue by funkyn3rd** [elucidsoft/dotnet-stellar-sdk#207]
I'm using version 2.2.14 because most recent versions don't recognize some secret keys...and it's bad, but, now, my main problem is that when I go to signing a transaction it give me error as a title.

Code is this:

 Dim transaction
masterAccount.IncrementSequenceNumber()
Dim operation As New PaymentOperation.Builder(destination, assettosend, NumericUpDown1.Value)
operation.Build()
transaction = New Transaction.Builder(masterAccount)
 transaction.AddOperation(operation.Build)
 transaction.addMemo(Memo.Text(TextBox2.Text))
transaction.build()
 Dim confirmSend = MsgBox("Send " & NumericUpDown1.Value & " " & Label3.Text & " to address " & TextBox1.Text & " ?", MsgBoxStyle.YesNo)
 If confirmSend = MsgBoxResult.Yes Then
transaction.sign(sourceKeys)-->**ERROR: 'Public member 'sign' on type 'Builder' not found.'**
End If

**Comment by Kirbyrawr** [comment]
Hi, may i know why in recent version it doesn't recognize some secret keys?

**Comment by funkyn3rd** [comment]
Please, can try to solve this issue first? Then I will post another Issue with Secret Key problem.
Anyway the secret key's problem in the most recent version is that some existing and used Secretkeys seems don't existing for the latest version fort example.
If I run the same code on 2.2.14, it recognize! Try your self!
But, please, can solve this issue first, then I oipen another Issue ticket  with all the code ;)

**Comment by funkyn3rd** [comment]
(thank you) ;)

**Comment by fracek** [comment]
I think the issue is that you're calling sign on `TransactionBuilder`, but you have to call it on the transaction built by the builder.

```vb
Dim transaction
masterAccount.IncrementSequenceNumber()
Dim operation As New PaymentOperation.Builder(destination, assettosend, NumericUpDown1.Value)
operation.Build()
transaction = New Transaction.Builder(masterAccount)
transaction.AddOperation(operation.Build)
transaction.addMemo(Memo.Text(TextBox2.Text))
Dim tx = transaction.build() ' Assign the return value to a tx variable that contains the transaction
Dim confirmSend = MsgBox("Send " & NumericUpDown1.Value & " " & Label3.Text & " to address " & TextBox1.Text & " ?", MsgBoxStyle.YesNo)
If confirmSend = MsgBoxResult.Yes Then
tx.sign(sourceKeys) ' Notice we sign tx 
End If
``

**Comment by elucidsoft** [comment]
If you are using TestNET those keys can disappear and are not guaranteed to persist.

**Comment by funkyn3rd** [comment]
Oh no,they are not testnet, i'm holding XLM in pub on these keys,they are created from js-stellar-sdk , this is one of the addresses: 
GDBLQEEE4XAQA23WNHIUX4OOHBZQQZNJMUYXN7ATFFGBGOHNKMS5V5AV
the secret Key of this address,for example, is not recognizable by latest version of dotnet SDK(for me) , it may be my error,this evening I will and post code here... this is very strange!!!! Anycase @fracek , I have corrected that error and now i have no error in my project but the transaction dont start,maybe because I have maked some issues with Sequence Number. I have extracted It from Json of my account in horizon.stellst.org into a Long Dim ..then next  I call the IncrementSequenceNumber() it's working in this way? Thank you
