### ISSUE TITLE
Transactions with MemoId fails to deserialize

### ISSUE THREAD

**Issue by fracek** [elucidsoft/dotnet-stellar-sdk#208]
**Describe the bug**
Trying to deserialize (some?) transactions with memo of type id fails with an exception.

**To Reproduce**

```
var tx = Transaction.FromEnvelopeXdr("AAAAAEdL24Ttos6RnqXCsn8duaV035/QZSC9RXw29IknigHpAAAD6AFb56cAAukDAAAAAQAAAAAAAAAAAAAAAF20fKAAAAACjCiEBz2CpG0AAAABAAAAAAAAAAEAAAAADq+QhtWseqhtnwRIFyZRdLMOVtIqzkujfzUQ22rwZuEAAAAAAAAAAGZeJLcAAAAAAAAAASeKAekAAABAE+X7cGoBhuJ5SDB8WH2B1ZA2RrWIXxGtx+n6wE5d/EggDTpZhRm92b33QqjPUFOfcZ+zbcM+Ny0WR2vcYHEXDA==");
```

**Expected behavior**

It should deserialise [correctly](https://www.stellar.org/laboratory/#xdr-viewer?input=AAAAAEdL24Ttos6RnqXCsn8duaV035%2FQZSC9RXw29IknigHpAAAD6AFb56cAAukDAAAAAQAAAAAAAAAAAAAAAF20fKAAAAACjCiEBz2CpG0AAAABAAAAAAAAAAEAAAAADq%2BQhtWseqhtnwRIFyZRdLMOVtIqzkujfzUQ22rwZuEAAAAAAAAAAGZeJLcAAAAAAAAAASeKAekAAABAE%2BX7cGoBhuJ5SDB8WH2B1ZA2RrWIXxGtx%2Bn6wE5d%2FEggDTpZhRm92b33QqjPUFOfcZ%2BzbcM%2BNy0WR2vcYHEXDA%3D%3D&type=TransactionEnvelope&network=public)

**Comment by fracek** [comment]
The problem is that the SDK considers a `MemoId` field to be `long`, when it is really a `ulong`. This particular transaction has an `Id` value that's greater than `Int64.MaxValue` and so it overflows, becoming negative.

In general, `UInt64` is always treated as `long` when it should be `ulong`.

@elucidsoft My fix involves changing `UInt64` to convert from/to `ulong`, then change all fields types to be `ulong`. In theory it's a breaking change, but if users really used signed values for `UInt64` fields their code is broken.

**Comment by elucidsoft** [comment]
I agree, and approve the change.

**Comment by elucidsoft** [comment]
Fixed in: https://github.com/elucidsoft/dotnet-stellar-sdk/releases/tag/3.0.13
