### ISSUE TITLE
Give no error but Transaction never start

### ISSUE THREAD

**Issue by funkyn3rd** [elucidsoft/dotnet-stellar-sdk#210]
![image](https://user-images.githubusercontent.com/56490798/68084597-ea5b0200-fe37-11e9-843b-6bf46893c84c.png)

What's i'm wrong???

**Comment by fracek** [comment]
`server.SubmitTransaction(tx)` returns a `Task`. I'm not an expert on VB.NET, but [this tutorial](https://www.dotnetperls.com/async-vbnet) should cover the basics of async/await in it.

**Comment by elucidsoft** [comment]
@funkyn3rd Does this need followup support? Please advise so we can close this issue. Thank you!

**Comment by funkyn3rd** [comment]
Not solved yet...Is It @fracek 's answer the right way? Repeat, no  errors, but transaction don't come in !
