### ISSUE TITLE
Re-submitting a "next page" request

### ISSUE THREAD

**Issue by bledbet** [elucidsoft/dotnet-stellar-sdk#213]
**Is your feature request related to a problem? Please describe.**
I could be missing something, but it seems that when paging through a resource (I'm working with Assets at the moment), if, say, a TooManyRequestsException is caught, there doesn't seem to be a good way to continue paging from the same place after waiting some time.

**Describe the solution you'd like**
I wonder if this is because Page.NextPage returns a Task rather than a RequestBuilder - if it returned a RequestBuilder, then I think, after catching TooManyRequestException and waiting some time, the caller can use the builder to create a new task for the same page, continuing where it left off.

**Describe alternatives you've considered**
Perhaps if Page exposed the cursor value (maybe I'm missing it), Server.Assets builder could be used to retry from .Cursor()

**Comment by elucidsoft** [comment]
@bledbet This is being looked at, just an FYI.

**Comment by Kirbyrawr** [comment]
Hi there, unless i'm missing something, you should be able to obtain it from 'Records' list under the name of paging_token.

Additionally you can parse it from the URLs in 'Links' parameter.

Let us know if that is ok for you!

**Comment by bledbet** [comment]
Hi - thanks for your response.  I see paging_token in the json payloads, but (apologies if I'm missing it) I'm not seeing where this value gets exposed by this library.  I do think I could work around it and just use the links, though.

**Comment by Kirbyrawr** [comment]
Should be in the `Records` list variable.

**Comment by Kirbyrawr** [comment]
https://github.com/elucidsoft/dotnet-stellar-sdk/blob/master/stellar-dotnet-sdk/responses/Page.cs#L20

**Comment by bledbet** [comment]
Thanks!
