### ISSUE TITLE
Update /fee_stats response

### ISSUE THREAD

**Issue by fracek** [elucidsoft/dotnet-stellar-sdk#216]
- ✂ Remove the following fields:

       min_accepted_fee
       mode_accepted_fee
       p10_accepted_fee
       p20_accepted_fee
       p30_accepted_fee
       p40_accepted_fee
       p50_accepted_fee
       p60_accepted_fee
       p70_accepted_fee
       p80_accepted_fee
       p90_accepted_fee
       p95_accepted_fee
       p99_accepted_fee
       

 - ➕Add support for `max_fee` and `fee_charged` fields. Each field contains a JSON object that looks like this:

       {
         "last_ledger": "22606298",
         "last_ledger_base_fee": "100",
         "ledger_capacity_usage": "0.97",
         "fee_charged": {
           "max": "100",
           "min": "100",
           "mode": "100",
           "p10": "100",
           "p20": "100",
           "p30": "100",
           "p40": "100",
           "p50": "100",
           "p60": "100",
           "p70": "100",
           "p80": "100",
           "p90": "100",
           "p95": "100",
           "p99": "100"
         },
         "max_fee": {
           "max": "100000",
           "min": "100",
           "mode": "100",
           "p10": "100",
           "p20": "100",
           "p30": "100",
           "p40": "100",
           "p50": "100",
           "p60": "100",
           "p70": "100",
           "p80": "100",
           "p90": "15000",
           "p95": "100000",
           "p99": "100000"
         }
        }
        

     See https://github.com/stellar/go/pull/2140 for more info.

**Comment by Kirbyrawr** [comment]
https://github.com/elucidsoft/dotnet-stellar-sdk/pull/215
