### ISSUE TITLE
Update fields that changed from long to String

### ISSUE THREAD

**Issue by fracek** [elucidsoft/dotnet-stellar-sdk#218]
🚨Multiple fields changed from `long` to `string`. If your SDK has types, they need to be updated. If possible, we recommend implementing backward compatibility support, as we did [here](https://github.com/stellar/go/blob/master/protocols/horizon/main.go#L258).

  - [x] Attribute `offer_id` in [manage buy offer](https://www.stellar.org/developers/horizon/reference/resources/operation.html#manage-buy-offer) and [manage sell offer](https://www.stellar.org/developers/horizon/reference/resources/operation.html#manage-sell-offer) operations.

  - [x] Attribute `offer_id` in `Trade` effect.

  - [x] Attribute `id` in [Offer](https://www.stellar.org/developers/horizon/reference/resources/offer.html) resource.

  - [x] Attribute `timestamp` and `trade_count` in [Trade Aggregation](https://www.stellar.org/developers/horizon/reference/resources/trade_aggregation.html) resource.

See https://github.com/stellar/go/issues/1609, https://github.com/stellar/go/pull/1909, and https://github.com/stellar/go/issues/1912 for more info

**Comment by Kirbyrawr** [comment]
https://github.com/elucidsoft/dotnet-stellar-sdk/pull/228
