### ISSUE TITLE
Regenerate XDR

### ISSUE THREAD

**Issue by fracek** [elucidsoft/dotnet-stellar-sdk#219]
♻ Regenerate the XDR definitions to include [MetaV2](https://github.com/jonjove/stellar-core/blob/b299b3a458a15f592352c67d4da69baa6e8fbb6a/src/xdr/Stellar-ledger.x#L309) support (also see [#1902](https://github.com/stellar/go/issues/1902)).

**Comment by Kirbyrawr** [comment]
On it

**Comment by Kirbyrawr** [comment]
https://github.com/elucidsoft/dotnet-stellar-sdk/pull/224
