### ISSUE TITLE
Support for Xamarin?

### ISSUE THREAD

**Issue by TylerEnp** [elucidsoft/dotnet-stellar-sdk#235]
When using the .sdk in a Xamarin Forms app, I encounter an error for the Android or iOS client (NSec may not be supported on this platform).  From my research, I believe this is due to the fact that NSec uses libSodium - which is itself a wrapper around an unmanaged C dll.   A possible workaround could be to compile libsodium - https://github.com/tabrath/libsodium-core/blob/master/Xamarin.md - also see here for details - https://stackoverflow.com/questions/52244224/which-libsodium-net-wrapper-to-use-when-building-cross-platform-apps-using-xama.  But, before I go do this route, I want to make sure I'm not missing something simple.  Should the sdk be working in Xamarin apps?  Will doing an OS-specific compile of libsodium work?

**Comment by Kirbyrawr** [comment]
Hi there it happened the same to me in Unity 3D i needed to compile the Libsodium libraries and do some changes, if you need help let me know.

**Comment by tylercmsft** [comment]
Hello, thank you for the reply, and offer for help.  Can you share a high-level set of steps that I would need to go through?

**Comment by TylerEnp** [comment]
Hello, thank you for the reply, and offer for help. Can you share a high-level set of steps that I would need to go through?

**Comment by Kirbyrawr** [comment]
Hi, i will try to get you tomorrow night, apologies!

**Comment by Kirbyrawr** [comment]
Hi @TylerEnp, in this repo you can find some scripts to build Libsodium for iOS and Android in a easy way https://github.com/netpyoung/unity.libsodium

When you have the libraries you need to try if NSec works with it, if it doesn't you will need to modify the check of the version at the start and maybe the way the library is imported in DLLImport atributte.

Basically you will want to look into building the libraries and modify NSec.

In my Unity Stellar repo i have the libraries created but they are a bit modified to work with Unity, however Xamarin and Unity is very similar so let me know if you have any errors or issues where you are stuck.

We will look into improve this workflow.

**Comment by Kirbyrawr** [comment]
Hi @TylerEnp can we close this issue or you need more info / help?

**Comment by TylerEnp** [comment]
Hello, Yes, thanks for your help.
