### ISSUE TITLE
Missing serializer for operation type PATH_PAYMENT_STRICT_SEND

### ISSUE THREAD

**Issue by eugeniuLivandovschi** [elucidsoft/dotnet-stellar-sdk#236]
**Describe the bug**
Missing serializer for operation type PATH_PAYMENT_STRICT_SEND
When a transaction is queried - the following error occurs

` Newtonsoft.Json.JsonSerializationException: Invalid operation 'type_i'='13'
   at stellar_dotnet_sdk.responses.OperationDeserializer.CreateResponse(Int32 type)
   at stellar_dotnet_sdk.responses.OperationDeserializer.ReadJson(JsonReader reader, Type objectType, OperationResponse existingValue, Boolean hasExistingValue, JsonSerializer serializer)`

**Comment by Kirbyrawr** [comment]
Hi, i will look into this today after work, apologies for the waiting time.

**Comment by Kirbyrawr** [comment]
Hi sorry again for my late response, looking into this now.

**Comment by Kirbyrawr** [comment]
I believe i found the issue, i will talk to the team and make a fix if that's the case. Thanks for the report.

**Comment by Kirbyrawr** [comment]
Hi @eugeniuLivandovschi somehow we missed to add that deserialization, i added it in this PR:
https://github.com/elucidsoft/dotnet-stellar-sdk/pull/237

**Comment by Kirbyrawr** [comment]
Thanks for the report, and apologies for the late reply.

**Comment by fracek** [comment]
This was fixed in #237. There will be a nuget release soon to make the fix available to everyone.

**Comment by elucidsoft** [comment]
Nuget Version 4.0.22 has been released that has this fix included.
