### ISSUE TITLE
Add support for CAP 18 trustline flags in effects and account response

### ISSUE THREAD

**Issue by elucidsoft** [elucidsoft/dotnet-stellar-sdk#243]
The upcoming stellar-core protocol 13 release will add support for CAP 18 ("Fine-Grained Control of Authorization").  Horizon has added a is_authorized_to_maintain_liabilities field to the account balance attributes. Also, there is now a new effect which indicates a trustline was authorized to maintain liabilities.  See stellar/go#2357 for more details.

**Copied from Java Project

**Comment by elucidsoft** [comment]
Test Bot

**Comment by Kirbyrawr** [comment]
https://github.com/elucidsoft/dotnet-stellar-sdk/pull/244
