### ISSUE TITLE
Add support for Fine-Grained Control of Authorization

### ISSUE THREAD

**Issue by fracek** [elucidsoft/dotnet-stellar-sdk#247]
[CAP 18](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0018.md) changed the data type for the attribute `authorize` in `AllowTrustOp`.  It is now a `uint32` instead of a `boolean`. It also includes a new `TrustLineFlag` which is `authorizedToMaintainLiabilitiesFlag` with value `2`.

You can see the implementation in `js-stellar-base` [here](https://github.com/stellar/js-stellar-base/blob/a15fc74c1f5d37e1a2a94bd610990ccea62292bb/src/operations/allow_trust.js#L34), which still accepts booleans but converts the value to an `uint32`.

This is part of #246

**Comment by Kirbyrawr** [comment]
Since we added the authorizedToMaintainLiabilities in other places i will follow the Java's code instead as i think is more easy to read.
https://github.com/stellar/java-stellar-sdk/pull/276/files#diff-dc1e56016276f11d48a7766517a79e9bR69

**Comment by Kirbyrawr** [comment]
I believe it's only these changes
https://github.com/elucidsoft/dotnet-stellar-sdk/pull/250

**Comment by fracek** [comment]
Fixed by #250
