### ISSUE TITLE
Implement a method for get value of a key from an account

### ISSUE THREAD

**Issue by Kirbyrawr** [elucidsoft/dotnet-stellar-sdk#25]
Implement a method for call an endpoint of Horizon and retrieve value (without load an account) from a specific key.

Example of URI:
https://horizon-testnet.stellar.org//accounts/GA7BNH4ET3A472B2YIWIATM27XQSUF5OTJXA2FNM7DY2BB4VCOZKOC7B/data/TestKey

Example of Code:
https://gist.github.com/Kirbyrawr/031575b0881d8430e9bd901437e19555

It would probably be something like this:
string value = new Account(NetworkId, AccountId)).GetData("key");

And additionally we can create two methods:
GetRawData("TestKey") == VGVzdFZhbHVl (Encoded)
GetData("Testkey") == TestValue (Decoded)

So maybe this belong to the Account object.

**Comment by michaeljmonte** [comment]
https://www.stellar.org/developers/horizon/reference/endpoints/data-for-account.html
