### ISSUE TITLE
PathStrictReceiveRequestBuilder and PathStrictSendRequestBuilder have wrong segments

### ISSUE THREAD

**Issue by gaclaudiu** [elucidsoft/dotnet-stellar-sdk#270]
**Describe the bug**
Builders for PathStrictReceive and PathStrictSend have wrong segments. 
"path/strict-receive" should be "paths/strict-receive"
"path/strict-send" should be "paths/strict-send".

With the current implementation Horizon returns : 
{
  "type": "https://stellar.org/horizon-errors/not_found",
  "title": "Resource Missing",
  "status": 404,
  "detail": "The resource at the url requested was not found.  This usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided."
}
**To Reproduce**
1. Try to execute a Path strict send or Path strict receive on testnet Horizon

**Expected behavior**
I should get a 200 status code and the paged records.

**Comment by fracek** [comment]
I opened a PR with the fix.
