### ISSUE TITLE
Fund Test Account through friendbot

### ISSUE THREAD

**Issue by jaglinux** [elucidsoft/dotnet-stellar-sdk#28]
**Is your feature request related to a problem? Please describe.**
When test account is created, it needs to be funded by friendbot. It would be useful if there is a utility to help with this.

**Comment by jaglinux** [comment]
Let me know if this is available, I can implement.

**Comment by Kirbyrawr** [comment]
I can take this task as well

**Comment by elucidsoft** [comment]
Yes if you want to implement please submit a PR and I will merge.

**Comment by jaglinux** [comment]
Please review PR : Add fund test account method #54

**Comment by elucidsoft** [comment]
Hello thanks for your PR, I went ahead and redid it using the Builder pattern we were using in the SDK.  Please take a look and you can use it for future reference on how to add things to the SDK.  Thanks again!
