### ISSUE TITLE
How to get Payment info(amount) from a transaction

### ISSUE THREAD

**Issue by layinka** [elucidsoft/dotnet-stellar-sdk#287]
Hi,
I can't seem to find a way to load a transaction (from a hash) and get the amount the sender paid for a payment operation.

In JS, the returned object returns an amount field, but i cannot find a similar field in this SDK,

Here is what i tried

```
var rBuilder = _stellarServer.Payments.ForAccount(account);
rBuilder = rBuilder.Limit(20);

Page<OperationResponse> pagedResponse = await rBuilder.Execute();

if (pagedResponse != null)
{
	foreach (var response in pagedResponse.Records)
	{
		if (response.TransactionSuccessful)
		{				
			var amount = response.Amount; // This field does not exist
		}
	}
}
```

I also tried this to try and load the transaction from the transaction hash , still no amount

```
var tx = await _stellarServer.Transactions.Transaction(transactionHash);
tx.Amount // This field does not exist
```

**Comment by fracek** [comment]
You are right that the `Amount` field is not present in the [`OperationResponse`](https://elucidsoft.github.io/dotnet-stellar-sdk/api/stellar_dotnet_sdk.responses.operations.OperationResponse.html) class, you need to cast it to [`PaymentOperationResponse`](https://elucidsoft.github.io/dotnet-stellar-sdk/api/stellar_dotnet_sdk.responses.operations.PaymentOperationResponse.html) before you can access the `Amount` field. In C# you can [pattern match on the object type](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/switch#pattern-matching-with-the-switch-statement):

```csharp
var rBuilder = _stellarServer.Payments.ForAccount(account);
rBuilder = rBuilder.Limit(20);

Page<OperationResponse> pagedResponse = await rBuilder.Execute();

if (pagedResponse != null)
{
	foreach (var response in pagedResponse.Records)
	{
		if (response.TransactionSuccessful)
		{	
                        switch (response)
                       {
                           case PaymentOperationResponse op:
                               var amount = response.Amount;
                               break;
                           default:
                               break;
                       }		
		}
	}
}
```

Similaryl for the case when you parse the transaction, you need to iterate over the transaction operations and match payment operations.

**Comment by layinka** [comment]
Alright thanks a lot
