### ISSUE TITLE
CreateClaimableBalance - Result Unknown OperationType 

### ISSUE THREAD

**Issue by edeharo77** [elucidsoft/dotnet-stellar-sdk#288]
**Description**
When processing the response of a CreateClaimableBalance, the class OperationResult throws the exception SystemException("Unknown OperationType");

**To Reproduce**
Steps to reproduce theSystemException("Unknown OperationType")
1. Create a transaction containing the operation CreateClaimableBalanceOperation
2. Submit the Stellar
3. Wait for the result

**Screenshots**
![image](https://user-images.githubusercontent.com/75883639/101982403-74d47e80-3c52-11eb-9a99-f9fd071c68ed.png)

**Additional context**
Missing case: {} for _stellar_dotnet_sdk.xdr. OperationType.CREATE_CLAIMABLE_BALANCE_ as well as s_tellar_dotnet_sdk.xdr. OperationType.CLAIM_CLAIMABLE_BALANCE_
![image](https://user-images.githubusercontent.com/75883639/101982615-07295200-3c54-11eb-926f-3d7e85613d50.png)

**Comment by Kirbyrawr** [comment]
Thanks for the report, i will be checking it today.

**Comment by Kirbyrawr** [comment]
https://github.com/elucidsoft/dotnet-stellar-sdk/pull/289
