### ISSUE TITLE
XLM does not have asset code in AccountResponse

### ISSUE THREAD

**Issue by yehor-ms** [elucidsoft/dotnet-stellar-sdk#295]
**Describe the bug**
XLM (Lumen/Native) does not have an asset code in account balances.

**To Reproduce**
https://elucidsoft.github.io/dotnet-stellar-sdk/tutorials/examples/get_account_balance.html

**Expected behavior**
XLM should have an asset code.

**Screenshots**
![image](https://user-images.githubusercontent.com/76120345/103305741-97b5af80-4a14-11eb-9719-a4fe5d067040.png)

**Desktop (please complete the following information):**
 - OS: win 10
 - Dotnet 5
- package: 6.0.31

**Additional context**
I am using a test network.
P.S. sorry for the bad English.

**Comment by yehor-ms** [comment]
So xlm does not have an asset code on horizon server response. Sorry if I wasted your time.   
{
      "balance": "9999.9999500",
      "buying_liabilities": "0.0000000",
      "selling_liabilities": "0.0000000",
      "asset_type": "native"
    }

**Comment by Kirbyrawr** [comment]
No worries! 

It's a common mistake, it happened to me many times, you can check in the documentation examples i believe it's explained there, but as you stated it's because in the response is not even there.
