### ISSUE TITLE
Response of SubmitTransaction is null

### ISSUE THREAD

**Issue by farukterzioglu** [elucidsoft/dotnet-stellar-sdk#296]
**Describe the bug**
From time to time while sending XLM via SubmitTransaction metod it returns null without further explanation. 
And also some of them appear on network after a while.

**To Reproduce**
Send some XLM (not every transaction fails)

**Expected behavior**
Transaction should appear in network or an exception should be return 

**Desktop**
OS: ubuntu 18.04
Dotnet 3.1
package: 6.0.31

**Additional context**
Related code
https://github.com/elucidsoft/dotnet-stellar-sdk/blob/dfa625fcd10e970384dadeeb6a89a75fb1b7bb9c/stellar-dotnet-sdk/Server.cs#L180

**Comment by fracek** [comment]
Are you able to reproduce this consistently or it's more of a random thing? What Horizon server are you using?

**Comment by farukterzioglu** [comment]
We are using https://horizon.stellar.org/ and this issue happening multiple times in a day.

We have lots of withdrawals (in an exchange) and we frequently requiring to check is these transactions sent or not by checking from block explorer.

**Comment by fracek** [comment]
Ok thank you. I will check with other devs if we can reproduce and see what's happening.

**Comment by elucidsoft** [comment]
At minimal this should bubble the exception instead of returning null.

**Comment by farukterzioglu** [comment]
How about adding a new option to `SubmitTransactionOptions` like `bool EnsureSuccess` and checking if the status code is success or not. If `EnsureSuccess` is true and status code is not success, a `ConnectionErrorException` could be thrown with status code and content (if there is any)

**Comment by fracek** [comment]
Good idea, we could call `HttpResponseMessage.EnsureSuccessStatusCode` if that option is set so the method would throw `HttpRequestException`. This way we are also backward compatible.

**Comment by farukterzioglu** [comment]
I also though to call `EnsureSuccessStatusCode ` but it doesn't return the content when it is available. 
How about checking for `IsSuccessStatusCode` then throwing a custom exception (like `ConnectionErrorException` in `federation` module) with status code and content (if available).

**Comment by farukterzioglu** [comment]
Made a quick implementation at https://github.com/BlockForks/dotnet-stellar-sdk/commit/b7d5cb3a5882f12e8e54e67b3c7c5d0578e93193

You can take a look. I can update it with further discussion and create a PR according to Contributing guide.

**Comment by fracek** [comment]
The implementation looks good. If you submit a PR I'll review it.
