### ISSUE TITLE
Change trust operation "limit" field optional

### ISSUE THREAD

**Issue by l3utterfly** [elucidsoft/dotnet-stellar-sdk#316]
According to stellar docs, the "limit" field should be optional for the change trust operation.

https://developers.stellar.org/docs/issuing-assets/how-to-issue-an-asset/

![image](https://user-images.githubusercontent.com/6970347/117419374-d4179000-af5f-11eb-9d59-3b550a815d83.png)

**Comment by Kirbyrawr** [comment]
Thanks for the report, i will take care of it soon!

**Comment by Kirbyrawr** [comment]
Here is the PR with the change.
https://github.com/elucidsoft/dotnet-stellar-sdk/pull/317

**Comment by elucidsoft** [comment]
Resolved in Release 7.1.3
