### ISSUE TITLE
API for Offers, Single Offer 

### ISSUE THREAD

**Issue by kthompson** [elucidsoft/dotnet-stellar-sdk#329]
**Is your feature request related to a problem? Please describe.**
I was looking for an API to get the current status of an Offer or set of offers but I am not able to find one. Maybe I haven't looked well enough?

**Describe the solution you'd like**
I would imagine there would be an API to get the results from this API:
https://laboratory.stellar.org/#explorer?resource=offers&endpoint=single&network=public (Offers, Single Offer)

**Describe alternatives you've considered**
There is currently a way to get all offers for an account. For now I think I can look through this list for the offers I am looking for to see if they have been cleared/completed.

**Comment by Kirbyrawr** [comment]
Did you check https://elucidsoft.github.io/dotnet-stellar-sdk/api/stellar_dotnet_sdk.requests.OffersRequestBuilder.html
? 

Let me know if it doesn't work for you

**Comment by kthompson** [comment]
Yea it doesn't have a way to show a single offer. ultimately i'm just trying to determine if an offer is completed but i think i found a way that works well enough via the Trades api and counting up the amounts for a given offer to see if they add up to the offer amount.
