### ISSUE TITLE
AssetResponse does not include liquidity_pools_amount

### ISSUE THREAD

**Issue by GuyWhoKnowsTheGuy** [elucidsoft/dotnet-stellar-sdk#347]
**Describe the bug**
`AssetResponse `does not include `liquidity_pools_amount`

**To Reproduce**
1. `var assetInfo = await Server.Assets.AssetIssuer( [ any existing account ID ] ).Execute();`
2. `assetInfo.LiquidityPoolsAmount` does not exist.  `LiquidityPoolsAmount `would map to `_embedded.records.liquidity_pools_amount`.

**Expected behavior**
`AssetResponse.LiquidityPoolsAmount` would exist and map to `_embedded.records.liquidity_pools_amount`.

**Comment by Kirbyrawr** [comment]
Check this to have a reference, it seems i missed adding it https://github.com/stellar/java-stellar-sdk/blob/master/src/main/java/org/stellar/sdk/responses/AssetResponse.java

**Comment by GuyWhoKnowsTheGuy** [comment]
Fixed in #348.
