### ISSUE TITLE
Payment [tx_insufficient_fee] error when source account has more than enough fees during load testing

### ISSUE THREAD

**Issue by l3utterfly** [elucidsoft/dotnet-stellar-sdk#353]
This error only seems to happen during load testing. I am submitting multiple payment transactions from multiple different accounts.

Often, some transactions will fail with the following error: https://laboratory.stellar.org/#xdr-viewer?input=AAAAAAAAAGX%2F%2F%2F%2F3AAAAAA%3D%3D&type=TransactionResult&network=test

Reading through Stellar docs, perhaps it is due to surge pricing? Could it be the transaction is not setting a maximum fee to pay?

I see the "fee" parameter being set in the transaction builder, but my understanding of the code is not enough to determine if that's just the base fee or the max fee to pay for each transaction?

**Comment by elucidsoft** [comment]
This appears to be an error from Horizon, have you tried asking the Horizon team why it does this?

**Comment by l3utterfly** [comment]
Ok, I will try and ask there

**Comment by Kirbyrawr** [comment]
Hi, did you clear the doubt you had? I saw this problem before in the past and is usually related to timeouts and fee surging, the code seems to be ok, however i want to clarify if we can close it or needs more investigation.

**Comment by l3utterfly** [comment]
I've not had any response from Horizon yet. But feel free to close it if you want. I will open a new issue if needed.
