### ISSUE TITLE
Desrialization through 

### ISSUE THREAD

**Issue by taxinvoice** [elucidsoft/dotnet-stellar-sdk#361]
private List<Balance> balances;

    protected override async Task OnInitializedAsync()
    {
        balances= await Http.GetFromJsonAsync<List<Balance>>($"balance");  ///get error
     }

I can serialize on the server but deserialization fails as below..i assume its something to do with json annontations on properties of balance?

Unhandled exception rendering component: Each parameter in the deserialization constructor on type 'stellar_dotnet_sdk.responses.Balance' must bind to an object property or field on deserialization. Each parameter name must match with a property or field on the object. The match can be case-insensitive.

**Comment by Kirbyrawr** [comment]
Hi, will take a look into it soon

**Comment by taxinvoice** [comment]
Fixed it, i replaced default serializer with Newtonsoft

**Comment by Kirbyrawr** [comment]
Thanks, sorry i couldn't check on time
