### ISSUE TITLE
Potential error for missing Retry-After header

### ISSUE THREAD

**Issue by vinamogit** [elucidsoft/dotnet-stellar-sdk#362]
https://github.com/elucidsoft/dotnet-stellar-sdk/blob/5ff3242c8be03c7c679ec125c6ac9544e6e0e1bb/stellar-dotnet-sdk/requests/ResponseHandler.cs#L17

The Retry-After header is not guaranteed to be sent by the horizon instance, this leads to an unexpected exception in Java implementation, reporting on dotnet for verification.

See stellar/java-stellar-sdk#433

**Comment by Kirbyrawr** [comment]
@elucidsoft can you do that please?
