### ISSUE TITLE
Issues when attempting to create Muxed Accounts

### ISSUE THREAD

**Issue by ArcosChris** [elucidsoft/dotnet-stellar-sdk#364]
I hope this is the best place to find answers to this issue. I have attempted many times to create muxed accounts using this SDK, but I continue to have this problem where any Muxed accounts that are created do not get created in stellar or become associated with the base account (G… Address). So once I make a muxed account and try to look for it in stellar expert or stellar lab, it won't come up, or it comes up with a different base account address. 
I also tried to do this with the JS SDK for testing purposes, and it works as intended. However, I am just lost, and I do not want to keep trying if I do it incorrectly. So please help me find a solution to this problem. Thank you. Please see the images below, which might explain this better. 

Also, I am newer to working with Stellar so if I am going about this the wrong way I would really appreciate any pointers. I tried looking everywhere for answers but cant seem to find any documentation on creating the Muxed Account with dotnet-stellar-sdk.

---JS Attempt 
![JSAttempt](https://user-images.githubusercontent.com/80923831/170393981-d87a3e60-31a8-4a85-b5c2-bdfba1c4517f.png)

![image](https://user-images.githubusercontent.com/80923831/170394022-c47fc086-15a3-4cdc-8c85-dabaf7c39556.png)

-- dotnet Issues
![image](https://user-images.githubusercontent.com/80923831/170394580-47df6ade-6cae-4676-9af0-2adb43a9518e.png)

![image](https://user-images.githubusercontent.com/80923831/170394779-261b479a-35a5-4fdd-88ac-1f00a2e04b65.png)

**Comment by Kirbyrawr** [comment]
Hi, it seems like this is a bug, i'm researching it but i suspect where it comes from, will write more when i have more information, thanks for the report.

**Comment by Kirbyrawr** [comment]
Hi, this is fixed now, thanks for the report.

**Comment by Kirbyrawr** [comment]
![imagen](https://user-images.githubusercontent.com/3259762/171064192-e0a3a8a3-ac77-4473-8ac1-d51719762c01.png)

**Comment by ArcosChris** [comment]
@Kirbyrawr Thank you so much. I really appreciate the work you guys do!

**Comment by Kirbyrawr** [comment]
Hi, i need to check the tests failing, but thats not a biggie, when the PR is reviewed and merged @elucidsoft will upload the Nuget, usually it doesnt take a lot of time, if you need to use it quickly you can also download the repo and use it outside of nuget but i recommend to wait.
Give it a day or two maximum

**Comment by Kirbyrawr** [comment]
Hi, tests are fixed now, it seems the decode was also bugged, i fixed both things and now it works with the XDR data, i will let @elucidsoft know.

**Comment by ArcosChris** [comment]
@Kirbyrawr no problem! thank you again

**Comment by Kirbyrawr** [comment]
@elucidsoft can you please take a look into the PR? Thanks!

**Comment by ArcosChris** [comment]
@Kirbyrawr is this just waiting on approval?

**Comment by Kirbyrawr** [comment]
Yeah, sadly @elucidsoft is having a lot of real life complications and he needs to focus on them. I don't know how we can handle this, maybe i can merge it directly.

**Comment by ArcosChris** [comment]
Oh man, no problem! I hope everything gets better.

**Comment by elucidsoft** [comment]
Thanks @Kirbyrawr and @ArcosChris for being patient while I deal with some stuff in my life. I am going to merge this now.

**Comment by ArcosChris** [comment]
@elucidsoft @Kirbyrawr Thank you both very much for your help with this.
