### ISSUE TITLE
Fixes exception thrown from ManageOfferOperation.fromXDR for certain offers

### ISSUE THREAD

**Issue by elucidsoft** [elucidsoft/dotnet-stellar-sdk#37]
We need to test to see if this issue also exists in the dotnet sdk.  If it does we need to fix it in a similar fashion to the Java SDK to stay as close to possible.

https://github.com/stellar/java-stellar-sdk/pull/97

**Comment by Kirbyrawr** [comment]
I will try to check this this weekend!

**Comment by Kirbyrawr** [comment]
Hi there after checking we don't have this issue, it parses the price properly without throwing any exception.

**Comment by Kirbyrawr** [comment]
![image](https://user-images.githubusercontent.com/3259762/43689367-bf88f536-98f9-11e8-95a7-3aac9bcef940.png)

**Comment by Kirbyrawr** [comment]
We should close it i think... Waiting for you @elucidsoft

**Comment by elucidsoft** [comment]
Is there a Unit test to cover this scenario?

**Comment by Kirbyrawr** [comment]
Yes i have it written but i didn't push it.

The main problem mostly is that when trying to parse the price it have too
many decimals and it seems that in java thats bad, here it doesn't happen.
