### ISSUE TITLE
use org.stellar.sdk.Price instead of String in org.stellar.sdk.ManageOfferOperation

### ISSUE THREAD

**Issue by elucidsoft** [elucidsoft/dotnet-stellar-sdk#39]
I think we should maintain both the string and the Price type, the new type will have a different name and we will maintain the old one as a string for backward compatibility and it's useful if you just want it as a string in some cases.

https://github.com/stellar/java-stellar-sdk/pull/108

**Comment by Kirbyrawr** [comment]
Hm that pull request was closed without merge...
