### ISSUE TITLE
Redo the Documentation

### ISSUE THREAD

**Issue by elucidsoft** [elucidsoft/dotnet-stellar-sdk#40]
I would like to redo our documentation, make it slick, and sexy something that's similar to https://stellar.github.io/js-stellar-sdk/ would be great.  Would like it done in a way that it's able to pick up the majority of the changes from the XML that's generated automatically by the build process.

**Comment by Kirbyrawr** [comment]
I would like to contribute with this, let me know if it's possible.

**Comment by Kirbyrawr** [comment]
Maybe we can use Sandcastle for this:
https://github.com/EWSoftware/SHFB

**Comment by elucidsoft** [comment]
My understanding of Sandcastle is it builds the old school chm style help files and not web pages?  I used something similar to build what we currently have but it's not very user-friendly IMO.  Perhaps we can modify what we currently have instead?  The current help is supposed to be a wiki format but I was not able to get the wiki stuff to work properly with GitHub pages.

**Comment by Kirbyrawr** [comment]
Actually i'm not sure how exactly it works, i'm going to try it now and see if it fits your idea.
I will research a bit more how to output the structure we have for not modify everything.

We can also use doxygen but that's a bit old i think..

**Comment by elucidsoft** [comment]
We are currently using DocFX, which looks they do have support for GitHub pages I just don't think its setup entirely correct.  

http://dotnet.github.io/docfx

**Comment by Kirbyrawr** [comment]
I will research it too and will report here when i have something so we can decide the path we want to take : )

**Comment by elucidsoft** [comment]
So the way it works currently is the docs folder is where all the documentation is at.  That path is where GitHub Pages is pointing at to host.  So when you go to the documentation URL https://elucidsoft.github.io/dotnet-stellar-sdk/ its using that location.

**Comment by Kirbyrawr** [comment]
I'm going to test in my fork and see what's the best way to do it based on your information, thank you!

**Comment by Kirbyrawr** [comment]
I will do the next:
-I will generate the documentation with the command line tool.
-I will try to add into the project in the docs folder or elsewhere all needed for generate this documentation (Maybe the .json file)
-I will add support for github pages (Saw already some things, going to try in my fork)

Maybe we can create a template and modify it as we like, i'm not pretty good on this but i will research how to do it.

**Comment by Kirbyrawr** [comment]
Hi @elucidsoft i managed to update the docs and all the links are working now correctly, you can check here:
https://kirbyrawr.github.io/dotnet-stellar-sdk/api/stellar_dotnet_sdk.html

What's the best way for merge those docs? I still need to put filters for the chaos libraries and make some improvements, but the main part is done.

**Comment by elucidsoft** [comment]
If you submit a PR I will merge it.  Looks great!

**Comment by Kirbyrawr** [comment]
I'm going to do some improvements and the pull request

**Comment by Kirbyrawr** [comment]
Assign this task to me if possible, i'm trying to customize the theme a bit  (css and icons) and excluding the Chaos.NaCl 

Thanks!

**Comment by elucidsoft** [comment]
I added you as a contributor but you need to accept it.

**Comment by Kirbyrawr** [comment]
Done!

**Comment by Kirbyrawr** [comment]
Hi, first of all, i never touched "CSS, HTML or TMPL" files, however i'm doing a custom template for the docs, probably i'm doing things wrong but so far is working and it's autoadjustable (still need to fix some mobile paddings).

![image](https://user-images.githubusercontent.com/3259762/41996682-f60efac8-7a55-11e8-9313-b74d6ae71d4a.png)

What do you think?

**Comment by elucidsoft** [comment]
Looks good to me!

**Comment by Kirbyrawr** [comment]
**PR**
https://github.com/elucidsoft/dotnet-stellar-sdk/pull/48

**TODO**
Generate the docs automatically when doing changes to the code.
Maybe a bit better template?
Guides in the documentation?

**Comment by elucidsoft** [comment]
Great job!

**Comment by Kirbyrawr** [comment]
Hi here it works, maybe the docs were updating?

**Comment by Kirbyrawr** [comment]
I however saw an issue and is that the View Source is actually going to my repo instead of yours, i will check it now.

**Comment by elucidsoft** [comment]
Did you click the "Improve this Doc" link on the right from the link I posted above? That's whats showing a not found for me.

**Comment by Kirbyrawr** [comment]
Yeah! Now i get it, i know why it's but i need to know how to change it, i'm fixing it : )!

**Comment by Kirbyrawr** [comment]
What do you think of creating a gh-pages branch? With this all should be fixed and the documentation doesn't depend on the main project itself, also it makes generating documentation way more easy.

**Comment by Kirbyrawr** [comment]
**PR**
https://github.com/elucidsoft/dotnet-stellar-sdk/pull/49

Fixed URLS leading to other repository or missing pages.

I will try to see how to do this properly in the future.

**Comment by Kirbyrawr** [comment]
Hi there, i will still be working on this this weekend for fix the issues it have and also for make a better template.

**Comment by Kirbyrawr** [comment]
Hi there, i didn't like the final result for the docs so i made something better.

I took a template (that is MIT License) from a github repo since i fucked up some important layouts and i prefer to have this ok.
The original template was a bit... retro or like old, at least the colors.

So i decided to change some things of this template and here is the result.
![image](https://user-images.githubusercontent.com/3259762/42118592-affb7be6-7c04-11e8-8b30-6ada28695b97.png)

I also did the next:
-Made a Shell Script for generate documentation.
-Added master branch for contribution.
-Did a logo for the documentation page.
-Added Github link for go to the repo.
-Changed font to a Google Font (Source Sans Pro) Since it's way cool.
-Research about how to generate the documents properly.

**Comment by Kirbyrawr** [comment]
The only thing i'm missing for have this task complete is:
-Define how and when we are going to build the docs.

The docs, should be done using master branch and later do a branch with those changes in case you want a PR, because it take the info from the remote for edit the view-source url of the button.

The improve this document works different and it's already configured in the docfx.json file.

**Comment by Kirbyrawr** [comment]
Something like this should work:
https://gist.github.com/Kirbyrawr/7da43a4a214d32a3821957c164497e7a

**Comment by elucidsoft** [comment]
It would need to work using travis-ci is my only concern with doing it that way. Or we would need to manually update that branch everytime a code change occurs.

**Comment by Kirbyrawr** [comment]
Maybe we can use this: https://docs.travis-ci.com/user/deployment/script/ ?

**Comment by elucidsoft** [comment]
I'll have to mess with it and see if I can get that working. For now I'm ok with having a separate branch.

**Comment by Kirbyrawr** [comment]
Ok perfect, i will upload the gh-pages then.

**Comment by Kirbyrawr** [comment]
Uploaded, if you set up the repo to track gh-pages for the docs we are ready.

**Comment by elucidsoft** [comment]
Ok that's been done.

**Comment by Kirbyrawr** [comment]
Ok i'm going to update again the documentation for fix the issues related to my sources.
I will run the script and it should work all ok.

Thanks!

**Comment by Kirbyrawr** [comment]
Seems like the script have issues for copying the files to the folder, checking them...

**Comment by Kirbyrawr** [comment]
Fixed, can you check if the gh-pages is still configured ok? I deleted all the files before and maybe it got unassigned...

**Comment by Kirbyrawr** [comment]
Pull request is here:
https://github.com/elucidsoft/dotnet-stellar-sdk/pull/51

The templates file were missing and some more things, i updated them accordingly and if you merge i will update the documentation with the shell script.

Sorry for the trouble but this is a painful task and i don't have a lot of ways for check if it's correct or not.

**Comment by Kirbyrawr** [comment]
There is something wrong in how git is tracking inside docfx folder, for some reason templates are not getting added...

**Comment by Kirbyrawr** [comment]
I'm starting to feel it was due to a bug in SourceTree 
![image](https://user-images.githubusercontent.com/3259762/42126991-528dbb1c-7c91-11e8-8074-31335b103f7b.png)

As you can see in the git bash console it's showing the folder but not in SourceTree, anyways i will u
pload the changes to docs-fix branch

**Comment by Kirbyrawr** [comment]
After all this pain and headaches now yes, it's finally done.
https://github.com/elucidsoft/dotnet-stellar-sdk/pull/52

**Comment by elucidsoft** [comment]
Man great job, really outstanding actually.  The little stellar icon with the C# written on the side is hilarious I love it!!

**Comment by Kirbyrawr** [comment]
Hah, thanks! , there is still room to improve sone things but step by step :)
