### ISSUE TITLE
Upgrade to .NET Core 2.1

### ISSUE THREAD

**Issue by elucidsoft** [elucidsoft/dotnet-stellar-sdk#41]
The .NET Core 2.0 EOL is on September 1st 2018.  We need to upgrade to .NET Core 2.1 which is an LTS version and will be supported for 3 years.

**Comment by fracek** [comment]
Anyone working on this? I have a project using .NET Core 2.1 so I might take a shot at this.

**Comment by Kirbyrawr** [comment]
Not here
