### ISSUE TITLE
Guides and examples for docs

### ISSUE THREAD

**Issue by Kirbyrawr** [elucidsoft/dotnet-stellar-sdk#53]
Having guides and examples on the docs would be a great addition for the C# Library and also for outside of this library.

**Comment by Kirbyrawr** [comment]
Hi @elucidsoft since i worked a lot with this SDK and also did some complex things related to Stellar, i feel like i will be able to do some guides and tutorials.

What kind of guides or tutorials do you think we need? 

Thanks!

**Comment by Kirbyrawr** [comment]
Hi @elucidsoft i was going to update changes i did to the docs (Added Guides and some things) but you enabled the protection of the branch so i can't update it.

Any hints?

**Comment by elucidsoft** [comment]
That just means you need to create a branch to make a change instead of
making changes directly.  Then the change will be merged into it from the
branch you created and after the merge is done we can remove the branch you
created.

**Comment by Kirbyrawr** [comment]
Hm the problem is that i'm actually generating the docs with the shell
script i created and it automatically do it.. Maybe i will need to modify
it then for do pr.

Thanks!

**Comment by Kirbyrawr** [comment]
I will do the following:
-Modify the Shell Script for have a menu with the next options:
 +Generate Documentation
 +Upload Documentation
 +Generate + Upload

The script will ask you for select an option, and in case you selected one with upload, it will ask you to input the branch where you want to upload it, this way we can test the documentation properly and also do pull requests.
I will make a new pr soon with this change.

Apart from this, i will be doing guides and tutorials for the devs to do multiple things, when i have some of them i will start doing pull requests to you, i will do them in bulks so that way you don't need to review a lot of files in the same pr.

**Comment by Kirbyrawr** [comment]
Some updates on this task:

**Shell Script**
I did a manager for take care of the documentation easily while we wait for travis or if we want to do it manually.
![image](https://user-images.githubusercontent.com/3259762/42538209-8e129f64-8497-11e8-8456-564b7e60ee5a.png)
It now accepts branch name when uploading.
I will make the PR of this soon.

**Examples**
I did two more guides, i'm planning to cover almost all the basics areas and i'm focusing a lot in make it easy for the user.

Here are a couple of screenshots of them.

**Get Account Balances**
![image](https://user-images.githubusercontent.com/3259762/42538410-21628a54-8498-11e8-93d6-4ae892c18637.png)

**Send Native Assets**
![image](https://user-images.githubusercontent.com/3259762/42538385-0bb3eed2-8498-11e8-83cb-4e2f3eed175a.png)

The examples are a first pass and will be improved over time.

I will make a PR of those examples soon as well.

**Comment by Kirbyrawr** [comment]
Shell Script Pull Request
https://github.com/elucidsoft/dotnet-stellar-sdk/pull/56

Documentation Examples Pull Request
https://github.com/elucidsoft/dotnet-stellar-sdk/pull/58

When the pull https://github.com/elucidsoft/dotnet-stellar-sdk/pull/58 is merged in master i can update the documentation webpage and do a PR.

I will do improvements on the assistant part, i will probably make an interface for it and add things like not allow to upload documentation that was generated from other branch than master.

**Comment by Kirbyrawr** [comment]
Some examples were added so we can close this task, i will open another one with a list of things we can do as examples / guides.
