### ISSUE TITLE
tx_bad_seq

### ISSUE THREAD

**Issue by khadar439** [elucidsoft/dotnet-stellar-sdk#6]
![tx_bad_seq image](https://user-images.githubusercontent.com/33127340/36107320-ad560162-103f-11e8-9ed7-89e7a4d882de.png)
 Network.UseTestNetwork();
            var server = new Server("https://horizon-testnet.stellar.org");

            var source = KeyPair.FromSecretSeed("SC7NSAPW6NRRRNIHDNLX2YRGLEZMYQAUD4DQBUO7JG4KFK2YWI3PIGKQ");
            var destination = KeyPair.FromAccountId("GB3VRVQNZ65ITQWWATGHYAQDV5JQYUTNUNGBH6TYNN6EIT35RPF5MZGG");
            await server.Accounts.Account(destination);

            long sequenceNumber = 31277021296328709L;
            var account = new Account(source, sequenceNumber);
            account.GetIncrementedSequenceNumber();

            var transaction1 = new Transaction.Builder(account)
    .AddOperation(new PaymentOperation.Builder(destination, new AssetTypeNative(), "1000").Build()).AddMemo(Memo.Text("Test Transaction"))
    .Build();

            transaction1.Sign(source);
            var s = await server.SubmitTransaction(transaction1);

hi i am getting tx_bad_seq every time , what ever the sequence number ,still the same result 
can anybody tell me how to generate the next sequence number?

**Comment by elucidsoft** [comment]
Sequence number must be +1 the previous transaction.

**Comment by khadar439** [comment]
long sequenceNumber = 31277021296328709L; 
      var account = new Account(source, sequenceNumber);
         account.GetIncrementedSequenceNumber();
hi for the first transaction i dont know my sequence number , if i give any sequence number will it work?

**Comment by elucidsoft** [comment]
You will need to get the last transaction to increment the sequence number
for your first which is technically the next.

**Comment by khadar439** [comment]
![image](https://user-images.githubusercontent.com/33127340/36258803-147ca2b2-1282-11e8-8cec-734157cb6282.png)

**Comment by NgendraK** [comment]
I am also Facing Same issue ,Please Tell the Solution if any one Got the Result

**Comment by michaeljmonte** [comment]
I've modified your original code so that it gets the proper sequence from Horizon for the source address.


```
           //Set up the keypairs.
            var sourceKP = KeyPair.FromSecretSeed("SC7NSAPW6NRRRNIHDNLX2YRGLEZMYQAUD4DQBUO7JG4KFK2YWI3PIGKQ");
            var destinationKP = KeyPair.FromAccountId("GB3VRVQNZ65ITQWWATGHYAQDV5JQYUTNUNGBH6TYNN6EIT35RPF5MZGG");
            var destinationResp = server.Accounts.Account(destinationKP).Result;

            Console.WriteLine("Destination Balances Before: ");
            foreach(var balance in destinationResp.Balances)
            {
                Console.WriteLine(String.Format("Asset Type: {0} | Asset Amount: {1}", balance.AssetType, balance.BalanceString));
            }


            //Get the source's latest squence number from Horizon.
            var sourceResp = server.Accounts.Account(sourceKP).Result;
            var sequenceNumber = sourceResp.SequenceNumber;

            //Build the source account using the current squence number.
            var sourceAccount = new Account(sourceKP, sequenceNumber);

            //Build the transaction.
            var transaction1 = new Transaction.Builder(sourceAccount)
                                              .AddOperation(new PaymentOperation.Builder(destinationKP, new AssetTypeNative(), "10").Build())
                                              .AddMemo(Memo.Text("Test Transaction"))
                                              .Build();

            //Sign the transaction.
            transaction1.Sign(sourceKP);

            //Submit the transaction.
            var s = server.SubmitTransaction(transaction1).Result;

            //Was there a transaction error?
            if (s.SubmitTransactionResponseExtras != null)
            {
                //Show the errors.
                Console.WriteLine("Transaction Failed: ");
                foreach (var error in s.SubmitTransactionResponseExtras.ExtrasResultCodes.OperationsResultCodes)
                {
                    Console.WriteLine(error);
                }
            }
            else
            {
                //Get the destination account.
                destinationResp = server.Accounts.Account(destinationKP).Result;

                //Show the balances after.
                Console.WriteLine();
                Console.WriteLine("Destination Balances After: ");
                foreach (var balance in destinationResp.Balances)
                {
                    Console.WriteLine(String.Format("Asset Type: {0} | Asset Amount: {1}", balance.AssetType, balance.BalanceString));
                }

            }

            Console.WriteLine("End");
```
Hope this helps.
