### ISSUE TITLE
Unsafe Code in Poly1305.cs

### ISSUE THREAD

**Issue by Kirbyrawr** [elucidsoft/dotnet-stellar-sdk#61]
**Describe the bug**
There are some lines of unsafe code in Poly1305 that prevents you to compile without unsafe mode in Release compilation.

**To Reproduce**
1. Compile in release mode.
2. Check the console for the errors in Poly1305.cs class.

**Expected behavior**
It should be fixed for allow you to compile without enabling unsafe mode.

**Comment by elucidsoft** [comment]
There are many unsafe sections beyond this and they are necessary. We won't
be able to compile without this flag.

**Comment by Kirbyrawr** [comment]
Hm, fair enough, closing it then!
Thank you
