### ISSUE TITLE
SBC and contributions

### ISSUE THREAD

**Issue by Kirbyrawr** [elucidsoft/dotnet-stellar-sdk#62]
Hi there, i saw that you can submit contributions to the Stellar Build Challenge, even if i do this because i want and i like to do it, i would like to know if you are ok with me to submit the contributions i did to this repo.

Thanks in advance.

**Comment by elucidsoft** [comment]
This project was already submitted to SBC therefore it's not permitted to
be submitted again. They do intend to give maintenance payments out to top
Open Source projects that have previously won an SBC but none have been
given to this project yet. I do plan to distribute this to all
collaborators of the project.

**Comment by Kirbyrawr** [comment]
Hi, the thing is that it seems that contributions to this repository are accepted in this SBC, that's why i'm not sure. 

And that's odd, if you were a top winner in the past you should talk to someone of Stellar in the Slack...

To be honest i don't mind sending it or not, i did with my projects but i wanted to be sure about this case. 

Thanks!

**Comment by Kirbyrawr** [comment]
After talk with someone of Stellar, they said that contributions are allowed so i will be submitting the pr's i did after creating a post in Galactic Talk, i will write it precisely so it doesn't mean i did the whole thing.

If you contributed to this repository i would say that you should do something like it since you are contributing to it too.

**Comment by elucidsoft** [comment]
Oh I see what you are saying, yes absolutely!  Feel free to submit yourself
to that for your contributions!

**Comment by Kirbyrawr** [comment]
Thank you !
