### ISSUE TITLE
Fix creating Memo.ReturnHash

### ISSUE THREAD

**Issue by elucidsoft** [elucidsoft/dotnet-stellar-sdk#66]
The Java SDK had this issue, we need to ensure this is not an issue in the dotnet sdk that was carried over.

https://github.com/stellar/java-stellar-sdk/pull/118

**Comment by Kirbyrawr** [comment]
I will take a look into it since it's a bit relate to the thing i'm doing, i will do another pr in case.

**Comment by Kirbyrawr** [comment]
I'm going to take this task

**Comment by Kirbyrawr** [comment]
Done https://github.com/elucidsoft/dotnet-stellar-sdk/pull/79
