### ISSUE TITLE
Documentation site is down

### ISSUE THREAD

**Issue by LuckyURE** [elucidsoft/dotnet-stellar-sdk#7]
Thank you for creating this excellent c# library and especially for support dotnet core!  

Just wanted to let you know that the link referenced for the documentation (https://elucidsoft.github.io/dotnetcore-stellar-sdk/) is not working.

I do see that it's included with the repo (even though it's very sparse right now) and so I'll use that as a work-around for now.  Thanks and keep up the great work!

**Comment by elucidsoft** [comment]
Fixed
