### ISSUE TITLE
Streams implemented?

### ISSUE THREAD

**Issue by LuckyURE** [elucidsoft/dotnet-stellar-sdk#8]
In the demo application the example shows:

```
//Streams are Maybe fixed? in this API until a resolution is found for the HttpClient issue
            Console.WriteLine("-- Streaming All New Operations On The Network --");

            server.Operations
                .Cursor("now")
                .Order(OrderDirection.ASC)
                .Stream((sender, response) => { ShowOperationResponse(response); })
                .Connect();
```

However, when I try to use it Stream doesn't seem to be implemented.  I made sure all the using statements were included, etc.  Am I missing something or is this the case?

**Comment by Jbelles** [comment]
Try pulling out the .Order(OrderDirection.ASC) line. I noticed some inconsistent behavior with this.

**Comment by LuckyURE** [comment]
Thank you for the suggest, and I tried that, but I still couldn't get it to go.

I went ahead and just build my own streaming method and am hitting the API myself and it's working great.  Perhaps when I have time I'll share the code or submit a PR with the fix.  Thanks again.

**Comment by elucidsoft** [comment]
Yes please submit a PR

**Comment by elucidsoft** [comment]
This seems to work, there are some quirks but those are dealing with Horizon and its load balancer....
